---
  - hosts: game
    become: true

    tasks:
      - name: Copy web page to remote directories(snake games)..
        copy:
          src: /opt/Ansible-Nginx/WebApp13/Game
          dest: /usr/share/nginx/

      - name: Copy nginx-config files to remote..
        copy:
          src: /opt/Ansible-Nginx/WebApp13/Configs/WebApp13-nginx.conf
          dest: /etc/nginx/conf.d/default.conf

  - hosts: basic_html   

    tasks:
      - name: Copy html page to remote
        copy: 
          src: /opt/Ansible-Nginx/WebApp14/html/
          dest: /usr/share/nginx/html/
        
      - name: Copy nginx-conf file to remote
        copy:
          src: /opt/Ansible-Nginx/WebApp14/Configs/WebApp14-nginx.conf
          dest: /etc/nginx/conf.d/default.conf
